weight: 1
maxAnimalsPerCell: 200
movementSpeed: 4
foodRequiredForSaturation: 0.15
maxAge: 10
maxPackNumber: 0
chanceToEat:
  Lynx: 0
  Wolf: 0
  Fox: 0
  Boa: 0
  Crow: 0
  Eagle: 0
  Bear: 0
  Sheep: 0
  Boar: 0
  Mouse: 0
  Horse: 0
  Rabbit: 0
  Goat: 0
  Hoatzin: 0
  Deer: 0
  Caterpillar: 90
  Buffalo: 0
  Plant: 100