weight: 2.0
maxAnimalsPerCell: 150
movementSpeed: 2
foodRequiredForSaturation: 0.45
chanceToEat:
  Lynx: 0
  Wolf: 0
  Fox: 0
  Boa: 0
  Crow: 0
  Eagle: 0
  Bear: 0
  Sheep: 0
  Boar: 0
  Mouse: 0
  Horse: 0
  Hoatzin: 0
  Goat: 0
  Duck: 0
  Deer: 0
  Caterpillar: 0
  Buffalo: 0
  Rabbit: 0
  Plant: 100